name: Build Portable Ruby 2.4.3 ARMHF

on:
  workflow_dispatch:

env:
  RUBY_VERSION: 2.4.3

jobs:
  build-ruby-armhf:
    runs-on: ubuntu-latest
    env:
      PREFIX: /opt/ruby-2.4.3
      HOST_PREFIX: /opt/ruby-host

    container:
      image: debian:bullseye

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup cross-compilation environment
        run: |
          apt-get update
          apt-get install -y \
            dpkg-dev \
            build-essential \
            curl \
            git \
            libssl-dev \
            libyaml-dev \
            libreadline-dev \
            zlib1g-dev \
            libffi-dev \
            gcc-arm-linux-gnueabihf \
            crossbuild-essential-armhf \
            libc6:armhf \
            libssl-dev:armhf \
            libyaml-dev:armhf \
            libreadline-dev:armhf \
            zlib1g-dev:armhf \
            libffi-dev:armhf

      - name: Download Ruby source
        run: |
          curl -O https://cache.ruby-lang.org/pub/ruby/2.4/ruby-${{ env.RUBY_VERSION }}.tar.gz
          tar -xzf ruby-${{ env.RUBY_VERSION }}.tar.gz

      - name: Build host Ruby
        run: |
          cd ruby-${{ env.RUBY_VERSION }}
          ./configure --prefix=${{ env.HOST_PREFIX }} --disable-install-doc
          make -j$(nproc)
          make install

      - name: Build Ruby for armhf
        run: |
          cd ruby-${{ env.RUBY_VERSION }}
          ./configure --host=arm-linux-gnueabihf --prefix=${{ env.PREFIX }} --with-baseruby=${{ env.HOST_PREFIX }}/bin/ruby --enable-shared
          make -j$(nproc)
          make install

      - name: Package Ruby installation
        run: |
          tar czf ruby-${{ env.RUBY_VERSION }}-armhf.tar.gz -C ${{ env.PREFIX }} .

      - name: Upload Ruby artifact
        uses: actions/upload-artifact@v4
        with:
          name: ruby-${{ env.RUBY_VERSION }}-armhf
          path: ruby-${{ env.RUBY_VERSION }}-armhf.tar.gz
          
