name: Build Portable Ruby 2.4.3 ARMHF

on:
  workflow_dispatch:

jobs:
  build-ruby-armhf:
    runs-on: ubuntu-latest
    container:
      image: debian:bullseye
    env:
      RUBY_VERSION: 2.4.3
      PREFIX: /opt/ruby-2.4.3

    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y \
            build-essential \
            curl \
            git \
            wget \
            libssl-dev \
            libyaml-dev \
            libreadline-dev \
            zlib1g-dev \
            libffi-dev \
            gcc \
            make \
            bison \
            autoconf \
            flex \
            texinfo \
            gawk \
            dpkg-dev \
            gcc-arm-linux-gnueabihf \
            crossbuild-essential-armhf

      - name: Build native Ruby 2.4.3 (host)
        run: |
          curl -O https://cache.ruby-lang.org/pub/ruby/2.4/ruby-2.4.3.tar.gz
          tar xzf ruby-2.4.3.tar.gz
          mv ruby-2.4.3 ruby-2.4.3-host
          cd ruby-2.4.3-host
          ./configure --prefix=/usr/local/ruby-2.4.3-host
          make -j$(nproc)
          make install

      - name: Cross-compile Ruby 2.4.3 for armhf
        run: |
          curl -O https://cache.ruby-lang.org/pub/ruby/2.4/ruby-2.4.3.tar.gz
          tar xzf ruby-2.4.3.tar.gz
          cd ruby-2.4.3
          ./configure --host=arm-linux-gnueabihf --prefix=${PREFIX} \
            --enable-shared --with-baseruby=/usr/local/ruby-2.4.3-host/bin/ruby
          make -j$(nproc)
          make install

      - name: Package Ruby installation
        run: |
          tar czf ruby-2.4.3-armhf.tar.gz -C ${PREFIX} .

      - name: Upload Ruby artifact
        uses: actions/upload-artifact@v4
        with:
          name: ruby-2.4.3-armhf
          path: ruby-2.4.3-armhf.tar.gz
          
