jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:10
        env:
          POSTGRES_USER: onodo
          POSTGRES_PASSWORD: password
          POSTGRES_DB: onodo
        ports: [5432]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.4.3

    - name: Set up Node and Yarn
      uses: actions/setup-node@v3
      with:
        node-version: 12

    - name: Install dependencies
      run: |
        bundle install
        yarn install

    - name: Set up database
      run: |
        cp config/database.yml.github config/database.yml
        bundle exec rake db:create db:migrate db:seed

    - name: Start server in background
      run: |
        nohup rails server -e test -p 3000 &
        sleep 10

    - name: Test server is responding
      run: |
        curl -f http://localhost:3000 || (echo "Server failed to start" && exit 1)
