name: Build Portable Ruby 2.4.3 ARMHF

on:
  workflow_dispatch:

jobs:
  build-ruby-armhf:
    runs-on: ubuntu-latest
    env:
      RUBY_VERSION: 2.4.3
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install dependencies for Ruby build
        run: |
          sudo dpkg --add-architecture armhf
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            curl \
            git \
            libssl-dev:armhf \
            libyaml-dev:armhf \
            libreadline-dev:armhf \
            zlib1g-dev:armhf \
            libffi-dev:armhf \
            gcc-arm-linux-gnueabihf \
            crossbuild-essential-armhf

      - name: Download Ruby 2.4.3 source
        run: |
          curl -O https://cache.ruby-lang.org/pub/ruby/2.4/ruby-2.4.3.tar.gz
          tar -xzf ruby-2.4.3.tar.gz

      - name: Configure and build Ruby for arm-linux-gnueabihf
        run: |
          PREFIX=/opt/ruby-$RUBY_VERSION
          cd ruby-2.4.3
          ./configure --host=arm-linux-gnueabihf --prefix=${PREFIX} --enable-shared
          make -j$(nproc)
          make install

      - name: Package Ruby installation
        run: |
          PREFIX=/opt/ruby-$RUBY_VERSION
          tar czf ruby-$RUBY_VERSION-armhf.tar.gz -C ${PREFIX} .

      - name: Upload Ruby artifact
        uses: actions/upload-artifact@v4
        with:
          name: ruby-2.4.3-armhf
          path: ruby-2.4.3-armhf.tar.gz
          
