name: Build Portable Ruby 2.4.3 ARMHF

on:
  workflow_dispatch:

jobs:
  build-ruby-armhf:
    runs-on: ubuntu-latest

    env:
      RUBY_VERSION: 2.4.3
      PREFIX: /opt/ruby-2.4.3

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          rm -r /var/lib/dpkg/arch-new
          dpkg --add-architecture armhf
          apt-get update
          sudo apt-get install -y \
            build-essential \
            curl git \
            autoconf bison libssl-dev libyaml-dev libreadline-dev zlib1g-dev libffi-dev \
            gcc-arm-linux-gnueabihf \
            crossbuild-essential-armhf \
            libssl-dev:armhf libyaml-dev:armhf libreadline-dev:armhf zlib1g-dev:armhf libffi-dev:armhf

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Download Ruby source
        run: |
          curl -O https://cache.ruby-lang.org/pub/ruby/2.4/ruby-2.4.3.tar.gz
          tar -xzf ruby-2.4.3.tar.gz
          cp -r ruby-2.4.3 ruby-2.4.3-armhf

      - name: Build host Ruby (x86_64)
        run: |
          cd ruby-2.4.3
          ./configure --prefix=$HOME/ruby-host
          make -j$(nproc)
          make install

      - name: Build ARMHF Ruby
        run: |
          cd ruby-2.4.3-armhf
          ./configure \
            --host=arm-linux-gnueabihf \
            --prefix=${PREFIX} \
            --enable-shared \
            --with-baseruby=$HOME/ruby-host/bin/ruby
          make -j$(nproc)
          make install

      - name: Package Ruby installation
        run: |
          tar -czf ruby-2.4.3-armhf.tar.gz -C ${PREFIX} .

      - name: Upload Ruby artifact
        uses: actions/upload-artifact@v4
        with:
          name: ruby-2.4.3-armhf
          path: ruby-2.4.3-armhf.tar.gz
          
