name: Cross-Compile Ruby 2.4.3 for ARMHF

on:
  workflow_dispatch:

jobs:
  build-armhf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            crossbuild-essential-armhf \
            curl \
            git \
            libssl-dev \
            libyaml-dev \
            libreadline-dev \
            zlib1g-dev \
            autoconf \
            bison \
            flex

      - name: Download Ruby 2.4.3
        run: |
          curl -fsSL https://cache.ruby-lang.org/pub/ruby/2.4/ruby-2.4.3.tar.gz | tar xz
          mv ruby-2.4.3 ruby-src
          cp -r ruby-src ruby-src-host
          mkdir ruby-build-host ruby-build-armhf

      - name: Build Full Ruby 2.4.3 for Host
        working-directory: ruby-src-host
        run: |
          ./configure --prefix=$GITHUB_WORKSPACE/ruby-build-host
          make -j$(nproc)
          make install

      - name: Cross-Compile Ruby 2.4.3 for ARMHF
        working-directory: ruby-src
        env:
          CC: arm-linux-gnueabihf-gcc
        run: |
          ./configure \
            --host=arm-linux-gnueabihf \
            --prefix=$GITHUB_WORKSPACE/ruby-build-armhf \
            --disable-install-doc \
            ac_cv_func_isnan=yes \
            ac_cv_func_isinf=yes \
            ac_cv_func_strlcpy=no

          # Use full host ruby for build scripts
          make RUBY=$GITHUB_WORKSPACE/ruby-build-host/bin/ruby -j$(nproc)
          make RUBY=$GITHUB_WORKSPACE/ruby-build-host/bin/ruby install

      - name: Package Ruby
        run: |
          tar czf ruby-2.4.3-armhf.tar.gz -C ruby-build-armhf .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ruby-2.4.3-armhf
          path: ruby-2.4.3-armhf.tar.gz
          
