name: Build Portable Ruby 2.4.3 ARMHF

on:
  workflow_dispatch:

jobs:
  build-ruby-armhf:
    runs-on: ubuntu-latest
    env:
      RUBY_VERSION: 2.4.3
      PREFIX_HOST: /opt/ruby-2.4.3-host
      PREFIX_ARMHF: /opt/ruby-2.4.3-armhf
      CROSS_COMPILE: arm-linux-gnueabihf-

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install dependencies for build
        run: |
          sudo dpkg --add-architecture armhf
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            curl \
            git \
            autoconf \
            bison \
            libssl-dev \
            libyaml-dev \
            libreadline-dev \
            zlib1g-dev \
            libffi-dev \
            gcc-arm-linux-gnueabihf \
            crossbuild-essential-armhf \
            libssl-dev:armhf \
            libyaml-dev:armhf \
            libreadline-dev:armhf \
            zlib1g-dev:armhf \
            libffi-dev:armhf

      - name: Download Ruby 2.4.3 source
        run: |
          curl -O https://cache.ruby-lang.org/pub/ruby/2.4/ruby-${RUBY_VERSION}.tar.gz
          tar -xzf ruby-${RUBY_VERSION}.tar.gz

      - name: Build host Ruby 2.4.3
        run: |
          cd ruby-${RUBY_VERSION}
          ./configure --prefix=${PREFIX_HOST} --enable-shared
          make -j$(nproc)
          sudo make install

      - name: Configure and cross-compile Ruby for armhf
        run: |
          cd ruby-${RUBY_VERSION}
          make clean
          ./configure --host=arm-linux-gnueabihf --prefix=${PREFIX_ARMHF} --enable-shared --with-baseruby=${PREFIX_HOST}/bin/ruby
          make -j$(nproc)
          make install

      - name: Package Ruby ARMHF installation
        run: |
          tar czf ruby-${RUBY_VERSION}-armhf.tar.gz -C ${PREFIX_ARMHF} .

      - name: Upload Ruby artifact
        uses: actions/upload-artifact@v4
        with:
          name: ruby-${RUBY_VERSION}-armhf
          path: ruby-${RUBY_VERSION}-armhf.tar.gz
          
