name: Build Ruby 2.4.3 for ARMHF (Cross-Compile)

on:
  workflow_dispatch:

jobs:
  build-armhf:
    name: Cross-compile Ruby 2.4.3 for ARMHF
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Cross-Compile Toolchain and Deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            crossbuild-essential-armhf \
            curl \
            git \
            libssl-dev \
            libffi-dev \
            libyaml-dev \
            libreadline-dev \
            zlib1g-dev \
            autoconf \
            bison \
            flex

      - name: Download Ruby Source
        run: |
          curl -fsSL https://cache.ruby-lang.org/pub/ruby/2.4/ruby-2.4.3.tar.gz | tar xz
          mv ruby-2.4.3 ruby-src
          mkdir -p ruby-build

      - name: Configure for Cross-Compile
        working-directory: ruby-src
        run: |
          ./configure \
            --host=arm-linux-gnueabihf \
            --prefix=$GITHUB_WORKSPACE/ruby-build \
            --disable-install-doc \
            ac_cv_func_isnan=yes \
            ac_cv_func_isinf=yes

      - name: Build Ruby
        working-directory: ruby-src
        run: |
          make -j$(nproc)
          make install

      - name: Package Compiled Ruby
        run: |
          tar czf ruby-2.4.3-armhf.tar.gz -C ruby-build .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ruby-2.4.3-armhf
          path: ruby-2.4.3-armhf.tar.gz
